// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;
using TotalClean.Models;

namespace TotalClean.Migrations
{
    [DbContext(typeof(MvcContext))]
    [Migration("20181109171945_qwe2")]
    partial class qwe2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("TotalClean.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Contraseña");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("TotalClean.Models.Oficina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ciudad")
                        .IsRequired();

                    b.Property<string>("Correo");

                    b.Property<DateTime>("Dia");

                    b.Property<string>("Direccion")
                        .IsRequired();

                    b.Property<string>("Distrito")
                        .IsRequired();

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<int>("Horas");

                    b.Property<int>("RUC");

                    b.Property<int?>("Telefono");

                    b.Property<string>("User")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Oficina");
                });

            modelBuilder.Entity("TotalClean.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos")
                        .IsRequired();

                    b.Property<string>("ConfirmarContraseña");

                    b.Property<string>("ConfirmarCorreo");

                    b.Property<string>("Contraseña")
                        .IsRequired();

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("User")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
